version: '3'

services:

  padel:

    build: 
      context: ./padel/
      dockerfile: padel.Dockerfile
    ports:
     - "5000:5000"
    
  requester:

    build: 
      context: ./requester/
      dockerfile: req.Dockerfile
    links:
     - padel
    
    stdin_open: true
    tty: true

