version: '3'

services:

  padel:

    build: 
      context: ./padel/
      dockerfile: padel.Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - data-volume:/opt/data
    tty: true
    
  requester:

    build: 
      context: ./requester/
      dockerfile: req.Dockerfile
    links:
     - padel
    volumes:
      - data-volume:/opt/data
    
    stdin_open: true
    tty: true

volumes:
  data-volume:
